// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fork_pending_config.sql

package db

import (
	"context"
)

const forkClaimPendingConfig = `-- name: ForkClaimPendingConfig :one
DELETE FROM host_pending_config
WHERE host_id = $1
RETURNING host_id, docker_enabled, compliance_enabled, compliance_on_demand_only, compliance_openscap_enabled, compliance_docker_bench_enabled, created_at, updated_at
`

// Atomically removes and returns a host's pending integration config.
// Exactly one concurrent caller gets the row; the others get no rows.
func (q *Queries) ForkClaimPendingConfig(ctx context.Context, hostID string) (HostPendingConfig, error) {
	row := q.db.QueryRow(ctx, forkClaimPendingConfig, hostID)
	var i HostPendingConfig
	err := row.Scan(
		&i.HostID,
		&i.DockerEnabled,
		&i.ComplianceEnabled,
		&i.ComplianceOnDemandOnly,
		&i.ComplianceOpenscapEnabled,
		&i.ComplianceDockerBenchEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
